import {
  Award,
  Ban,
  CalendarDays,
  CheckCircle2,
  Circle,
  Clock3,
  FileText,
  HelpCircle,
  MapPin,
  PauseCircle,
  RotateCcw,
  Search,
  Stamp,
  TriangleAlert,
  UserCheck,
  XCircle,
  type LucideIcon,
} from "lucide-react";
import type { StatusIcon as StatusIconKey } from "@/lib/status";

export const STATUS_ICONS: Record<StatusIconKey, LucideIcon> = {
  check: CheckCircle2,
  clock: Clock3,
  alert: TriangleAlert,
  x: XCircle,
  ban: Ban,
  file: FileText,
  search: Search,
  calendar: CalendarDays,
  user: UserCheck,
  map: MapPin,
  stamp: Stamp,
  award: Award,
  pause: PauseCircle,
  rotate: RotateCcw,
  circle: Circle,
  help: HelpCircle,
};
